# Generated by Django 3.2.12 on 2022-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20220618_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='info',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
