# Generated by Django 3.2.12 on 2022-06-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('reason', models.TextField(max_length=100)),
            ],
        ),
    ]
