# Generated by Django 3.2.12 on 2022-06-23 23:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 23, 36, 1, 925528, tzinfo=utc)),
        ),
    ]
