# Generated by Django 3.2.12 on 2022-06-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(max_length=50)),
                ('info', models.TextField(max_length=150)),
                ('img', models.ImageField(upload_to='section')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Sub_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=150)),
                ('img', models.ImageField(upload_to='sub-section')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.section')),
            ],
        ),
    ]
